CREATE TABLE IF NOT EXISTS SALARY(
EMPLOYEE TEXT ,
SALARY REAL ,
EMPLOYEEID TEXT PRIMARY KEY ,
DEPARTMENTS TEXT );

INSERT INTO SALARY(EMPLOYEE , SALARY , EMPLOYEEID , DEPARTMENTS) VALUES
('John Doe' , 50000 , 'E001' , 'HR' ) ,
('Jane Smith' , 60000 , 'E002' , 'IT' ) ,
('Emily Davis' , 55000 , 'E003' , 'Finance' ) ,
('Michael Brown' , 45000 , 'E004' , 'IT' ) ,
('Sarah Wilson' , 70000 , 'E005' , 'HR' ) ,
('David Lee' , 48000 , 'E006' , 'Finance' ) ;

SELECT SUM(SALARY) AS TotalSalary FROM SALARY ;
SELECT AVG(SALARY) AS AverageSalary FROM SALARY ;
SELECT COUNT(DEPARTMENTS) AS DepartmentCount FROM SALARY ;
SELECT MIN(SALARY) AS MinimumSalary FROM SALARY ;
SELECT MAX(SALARY) AS MaximumSalary FROM SALARY ;