CREATE TABLE IF NOT EXISTS PRODUCTS (
 PRODUCTID TEXT PRIMARY KEY,
 PRODUCTNAME TEXT ,
 SUPPLIERID TEXT ,
 CATEGORYID TEXT ,
 UNIT TEXT ,
 PRICE REAL );

 --Insert sample data into the PRODUCTS table
INSERT INTO PRODUCTS(PRODUCTID , PRODUCTNAME , SUPPLIERID , CATEGORYID , UNIT , PRICE) VALUES
('P001' , 'Laptop' , 'S001' , 'C001' , 'pcs' , 50000) ,
('P002' , 'Mouse' , 'S002' , 'C002' , 'pcs' , 500) ,
('P003' , 'Keyboard' , 'S003' , 'C002' , 'pcs' , 1000) ,
('P004' , 'Monitor' , 'S001' , 'C001' , 'pcs' , 1500) ,
('P005' , 'Printer' , 'S002' , 'C003' , 'pcs' , 800) ,
('P006' , 'Scanner' , 'S003' , 'C003' , 'pcs' , 6000) ;

SELECT COUNT(PRODUCTID) AS ProductCount FROM PRODUCTS ;

SELECT AVG(PRICE) AS AveragePrice FROM PRODUCTS ;

SELECT SUM(PRICE) AS TotalPrice FROM PRODUCTS ;

SELECT DISTINCT CATEGORYID FROM PRODUCTS  WHERE PRICE > 1000;


