CREATE TABLE IF NOT EXISTS PRODUCT(
PROID TEXT PRIMARY KEY ,
NAME TEXT ,
PRICE TEXT ,
COM TEXT );
INSERT INTO PRODUCT (PROID , NAME , PRICE , COM) 
VALUES
('1' , 'LAPTOP' , '50000' , 'XYZ COMPANY' ),
('2' , 'MOUSE' , '500' , 'ABC COMPANY' ),
('3' , 'KEYBOARD' , '1000' , 'DEF COMPANY' ) ,
('4' , 'MONITOR' , '15000' , 'GHI COMPANY' ),
('5' , 'PRINTER' , '8000' , 'JKL COMPANY' ),
('6' , 'SCANNER' , '6000' , 'MNO COMPANY' ) ;

SELECT NAME , PRICE FROM PRODUCT WHERE PRICE = 
(SELECT MIN(PRICE) FROM PRODUCT ) ;
SELECT NAME , PRICE FROM PRODUCT WHERE PRICE =
(SELECT MAX(PRICE) FROM PRODUCT ) ;
